name: update_files
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'          
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py_expression_eval
          pip install pydantic
          pip install orjson
      - name: execute        
        run: |
          python main.py
      - name: jq
        run: sudo apt-get update -y && sudo apt-get install -y jq
      - name: counting
        run: |
          echo "COUNT=$(jq '.SpectralIndices | length' ./output/spectral-indices-dict.json)" >> $GITHUB_ENV
      - name: badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 5e9f08fa6a45d9d486e29d9d85ad5c84
          filename: spectral.json
          label: Spectral Indices
          message: ${{ env.COUNT }}
          color: blue
          labelColor: gray
          namedLogo: Google Earth
      - name: commit
        continue-on-error: true
        run: |
          today=$(date +"%Y-%m-%d %H:%M:%S")
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Updated files ${today} UTC" -a
      - name: push
        continue-on-error: true
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main